apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: full-tracing
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100.0